name: migrate

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          tags: tag:github-action

      - name: Migrate with flyway
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/flyway/sql \
            redgate/flyway:latest \
            -url=jdbc:postgresql://100.88.57.69:5432/maechuri \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            migrate
